export const motivationalQuotes: string[] = [
  "En man är summan av sina handlingar, inte sina avsikter.",
  "Klagomål löser inga problem. Disciplinerad ansträngning gör det.",
  "Verkligheten är din enda domare. Argument är meningslösa.",
  "Den som skyller på andra har gett bort sin makt att förändra.",
  "Smärta är oundvikligt. Lidande är ett val.",
  "Bygg i tystnad. Låt dina resultat föra oväsen.",
  "Ditt sinne är ett verktyg. Använd det, eller bli använd av det.",
  "Välj den svåra vägen. Där är konkurrensen mindre.",
  "Medelmåttighet är en fiende som förklär sig till komfort.",
  "Värde skapas, det upptäcks inte.",
  "Sök inte respekt, sök att bli oumbärlig.",
  "Den mest effektiva formen av övertalning är resultat.",
  "Dina känslor är dina, inte sanningens.",
  "En plan som genomförs våldsamt nu är bättre än en perfekt plan nästa vecka.",
  "Sanningen bryr sig inte om hur du känner för den.",
  "Var herre över dina verktyg, inte en slav under dem.",
  "Slumpen gynnar det förberedda sinnet.",
  "Svaghet är en provokation.",
  "Tala inte om din filosofi, förkroppsliga den.",
  "Du är inte berättigad till dina åsikter, bara till vad du kan argumentera för.",
  "Den som jagar två kaniner fångar ingen.",
  "Ordning är grunden för all makt.",
  "Självkontroll är den yttersta formen av styrka.",
  "Leta inte efter motivation. Leta efter disciplin.",
  "En ursäkt är en logisk förklaring till ett misslyckande.",
  "Det finns inget substitut för handling.",
  "Fokusera på vad du kan kontrollera. Ignorera resten.",
  "Effektivitet är den sanna måttstocken på intelligens.",
  "Låt dina handlingar tala så högt att ingen hör vad du säger.",
  "Det du undviker att konfrontera kommer att styra dig.",
  "Var farlig, men disciplinerad.",
  "Det är inte jobbet att göra dig lycklig, det är ditt jobb att hitta lycka i jobbet.",
  "Den som vet 'hur' kommer alltid ha ett jobb. Den som vet 'varför' kommer alltid vara chef.",
  "Ignorera vad folk säger. Titta bara på vad de gör.",
  "En lugn sjöman blir inte skicklig på ett lugnt hav.",
  "Ju mer du svettas i träning, desto mindre blöder du i strid. — George S. Patton",
  "Logik är det bästa vapnet mot kaos.",
  "Sök sanningen, inte bekvämligheten.",
  "Resultat kräver ambition, inte åsikter.",
  "En man kan inte bygga ett rykte på vad han tänker göra. — Henry Ford",
  "Det är bättre att vara en krigare i en trädgård än en trädgårdsmästare i ett krig.",
  "Det finns ingen tillväxt i komfortzonen.",
  "Ambition är vägen till framgång. Uthållighet är fordonet du anländer i.",
  "Slösa inte tid på att förklara dig. Folk hör bara vad de vill höra.",
  "Det du äger, äger dig.",
  "Var den man du skulle vilja att din dotter gifte sig med.",
  "Ett problem upphör att vara ett problem när du har en lösning.",
  "Var skeptisk till allt som gör livet enklare på bekostnad av frihet.",
  "Målet är inte att leva för evigt, utan att skapa något som gör det.",
  "Svåra tider skapar starka män.",
  "Starka män skapar goda tider.",
  "Goda tider skapar svaga män.",
  "Svaga män skapar svåra tider.",
  "Lär dig reglerna som ett proffs, så att du kan bryta dem som en konstnär. — Pablo Picasso",
  "Sluta be om lov.",
  "Det är karaktär att göra det rätta när ingen ser på.",
  "Om du inte bygger din dröm, kommer någon att anställa dig för att bygga sin.",
  "Vinnare fokuserar på att vinna. Förlorare fokuserar på vinnare.",
  "Den bästa tiden att agera var igår. Den näst bästa är nu.",
  "Var en man av substans, inte av åsikt.",
  "Kaos är en stege. — Petyr Baelish",
  "En man som inte står för något kommer att falla för allt.",
  "Om du är den smartaste personen i rummet, är du i fel rum.",
  "Var försiktig med vems råd du tar. De flesta ger råd baserat på sina egna misslyckanden.",
  "Tålamod är inte att vänta, det är att ha en bra attityd medan man arbetar hårt.",
  "Du kan inte förhandla med en tiger när ditt huvud är i dess mun.",
  "En man definieras av de problem han väljer att lösa.",
  "Den som offrar frihet för säkerhet förtjänar varken och kommer att förlora båda. — Benjamin Franklin",
  "Var systematisk. Var obeveklig.",
  "Det finns ingen ära i förebyggande av misslyckande.",
  "Det du tillåter är det som kommer att fortsätta.",
  "Anpassa dig eller dö.",
  "Det är inte stress som dödar oss, det är vår reaktion på den.",
  "Förmögenhet byggs inte på lön, den byggs på tillgångar.",
  "Var inte upptagen, var produktiv.",
  "En handling slår tusen avsikter.",
  "Om det var lätt skulle alla göra det.",
  "Det du matar ditt sinne med bestämmer din aptit.",
  "Varför, inte hur, är den viktigaste frågan.",
  "Att vara ensam är en makt få kan hantera.",
  "Det största hindret för kunskap är inte okunskap, det är illusionen av kunskap.",
  "Bygg din kropp som en fästning, ditt sinne som ett vapen.",
  "Lär dig att se. Inse att allt hänger samman med allt annat.",
  "Sluta vänta på att känna dig redo.",
  "Kompetens är den enda verkliga säkerheten.",
  "Offra vad du är för vad du kommer att bli.",
  "En man kan inte upptäcka nya hav om han inte har modet att förlora stranden ur sikte. — André Gide",
  "Var den grå mannen. Osynlig men effektiv.",
  "Ingen kommer för att rädda dig. Ditt liv är 100% ditt ansvar.",
  "Det enda enkla dagen var igår. — Navy SEALs",
  "Du är inte din tanke, du är observatören av din tanke.",
  "En man med en klocka vet vad klockan är. En man med två klockor är aldrig säker.",
  "Gör det. Och om du är rädd, gör det rädd.",
  "Strategi utan taktik är den långsammaste vägen till seger. Taktik utan strategi är bullret före nederlag. — Sun Tzu",
  "Lyssna mer än du talar. Det är därför du har två öron och en mun.",
  "Var en student, inte en följare.",
  "Det är inte vad du tittar på som betyder något, det är vad du ser."
];